### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by jmastr** [rddl-network/rddl-prometheus-exporter#12]
the testnet lately gets a bit more unstable leading to long wait time to ssh into the machine, loading journals and so on. the thing that i noticed is that the prom exporter takes up up to 50% of the memory. is that intended? can we reduce the mem usage?

![2024-09-02T11:26:32,757469985+02:00](https://github.com/user-attachments/assets/523da886-4b7a-40ad-a2de-337f82e1c6d8)

**Comment by jmastr** [comment]
from testnet-1 at Mon Sep  2 11:21:29 UTC 2024:
```
 120103 ubuntu    20   0 1765588 143616  20480 S   0.7   3.6   0:24.89 rddl-prometheus
```

**Comment by LaurentMontBlanc** [comment]
let's see how it changes until tomorrow. I think the problem lies within a not closed grpc connection that is repeatedly opened. fix on this branch: https://github.com/rddl-network/rddl-prometheus-exporter/tree/fix-defer-on-planetmint-grpc-conn

**Comment by jmastr** [comment]
from testnet-1 at Tue Sep  3 06:07:59 UTC 2024:
```
 120103 ubuntu    20   0 2035772 407680  20608 S   0.3  10.3   7:16.58 rddl-prometheus
```

**Comment by jmastr** [comment]
after merging #13:
```
 124196 ubuntu    20   0 1697216  33408  20736 S   0.7   0.8   0:00.34 rddl-prometheus
```
let's keep the ticket open for a bit to see if the issue is fixed.
